//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridMvc.Resources {
    using System;
    
   
    internal class Strings {
        

        /// <summary>
        ///   Looks up a localized string similar to There are no items to display.
        /// </summary>
        internal static string DefaultGridEmptyText {
            get {
                return "There are no items to display";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter this column.
        /// </summary>
        internal static string FilterButtonTooltipText {
            get {
                return "Filter this column";
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string Lang {
            get {
                return "en";
            }
        }
    }
}
